# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: 'en'

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - daivik007/Rooting-A70s
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Daivik007's Links"

# Avatar image path
avatar: './images/profile.jpg'

# Name section text
name: '@Daivik007'

# Tagline section text
tagline: >-
  A UI UX Designer, Video Editor and a Graphic Designer from India 🇮🇳 who also loves sharing, traveling, and coding.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: 'fa-brands fa-instagram'
      text: 'Instagram'
      url: 'https://instagram.com/daivikk.07'
      alt: "Daivik's Instagram"
      title: "Daivik's Instagram"
      target: '_blank'
  - link:
      icon: 'fa-brands fa-x-twitter'
      text: 'Twitter'
      url: 'https://x.com/daivikk07'
      alt: "Daivik's Twitter"
      title: "Daivik's Twitter"
      target: '_blank'
  - link:
      icon: 'fa-brands fa-linkedin'
      text: 'LinkedIn'
      url: 'https://www.linkedin.com/in/daivik-trivedi-0b2a8b336/'
      alt: "Daivik's LinkedIn"
      title: "Daivik's LinkedIn"
      target: '_blank'
  - link:
      icon: 'fa-brands fa-dribbble'
      text: 'Dribbble'
      url: 'https://dribbble.com/daivik_07'
      alt: "Daivik's Dribbble"
      title: "Daivik's Dribbble"
      target: '_blank'
  - link:
      icon: 'fa-brands fa-github'
      text: 'GitHub'
      url: 'https://github.com/daivik007'
      alt: "Daivik's GitHub"
      title: "Daivik's GitHub"
      target: '_blank'
  - link:
      icon: 'fa-brands fa-behance'
      text: 'Behance'
      url: 'https://www.behance.net/daiviktrivedi'
      alt: "Daivik's Behance"
      title: "Daivik's Behance"
      target: '_blank'
  - link:
      icon: 'fa-brands fa-youtube'
      text: 'YouTube'
      url: 'https://www.youtube.com/@Daivooks07'
      alt: "Daivik's YouTube"
      title: "Daivik's YouTube"
      target: '_blank'

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: 'fa-brands fa-dribbble'
      url: 'https://dribbble.com/daivik_07'
      title: 'Dribbble'
      alt: "Daivik's Dribbble"
      target: '_blank'
  - social:
      icon: 'fa-brands fa-github'
      url: 'https://github.com/daivik007'
      title: 'GitHub'
      alt: "Daivik's GitHub"
      target: '_blank'
  - social:
      icon: 'fa-brands fa-twitter'
      url: 'https://twitter.com/daivikk07'
      title: 'Twitter'
      alt: "Daivik's Twitter"
      target: '_blank'
  - social:
      icon: 'fa-brands fa-linkedin'
      url: 'https://www.linkedin.com/in/daivik-trivedi-0b2a8b336/'
      title: 'LinkedIn'
      alt: "Daivik's LinkedIn"
      target: '_blank'
  - social:
      icon: 'fa-brands fa-instagram'
      url: 'https://www.instagram.com/daivikk.07/'
      title: 'Instagram'
      alt: "Daivik's Instagram"
      target: '_blank'
  - social:
      icon: 'fa-solid fa-envelope'
      url: 'mailto:daivik.n.trivedi@gmail.com'
      title: 'Email: daivik.n.trivedi@gmail.com'
      alt: 'daivik.n.trivedi@gmail.com'
      target: '_blank'

# Footer text
footer: >
  Hi there! Follow me on Dribbble or GitHub, or stay connected on Instagram or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025 Powered by <a href="https://github.com/daivik007/daivik007.github.io" target="_blank">Github Pages</a>
